language: node_js
node_js:
  - 11.10.1
cache:
  directories:
    - node_modules
env:
  global:
    - CODECOV_TOKEN=7ab7e761-055f-4ed0-bbbd-69d02d25faec
    - secure: FUPtmvGh8/eRGfMKa7QqQYArVUX1eok1HN7s1bufBpGhL+WATRxHx39qPf+3mvox//LZ7jIA6dxJ7oT6d8HbmJN4kIIsDF3eoKU4BxO5U+5znzSdwIBpz4lI9vNmbibvp9rikBFBaWPoXWgkzpxueJgj2C95rHCj+Nmiyq0GZV1fn5Pq0FG5y5PMxk3oGkn9igFTYEyqoTUmESSvUmo1foZEaZkCscGWuAoT3zqGUeM1sYUlSw+pj0UueBD79idc/aCDQYzA1IFvQxpPnKVlJqwbkFKyQGOPsi012NphOnCa/mnqN7wI6H20XNEOen1T9LVlPQg8ZUpM/fEDq94E36aIheIe45jq5DyUwOFWljUqnjcgNa4HsWa9vvIXi1BLpYwqvQfZJCRkTsrKz1puLtDpUdIn59To3+Co10WurGdAHgL2AXzKQTUJPlSR8I1EqHMcBFB8QtxJh6mCDFSkBTncyEySJ/zaWqbUdAKlFmOFYIO6Hue0CLjB/dWcoE2X4XcA5YAb3yt5a6rgzb+EQJJxXljs6ifcLkCcnjZqMYFtIU2IiiQixwDkFR8Jpt1PABLU8uEf7fBBdONUn6BxWO1KUyAC1rMMBMlaogqmcKts5+4e2mpxaNeiPjvZ1/Qd3zCG3Z6dHQll/YEZBiwZzmz4O1v7UhbBptNYx/Dmoz0=
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
script:
  - npm test
  - npm run test:coverage
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: build
  on:
    branch: master
