language: node_js
node_js:
  - "11.10.1"
cache:
  directories:
    - node_modules
env:
  global: CODECOV_TOKEN=7ab7e761-055f-4ed0-bbbd-69d02d25faec
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
script:
  - npm test
  - npm run test:coverage
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  REACT_APP_GET_ME_IN: $_GET_ME_IN
  local_dir: build
  on:
    branch: master
