language: node_js
node_js:
  - 11.10.1
cache:
  directories:
    - node_modules
env:
  global:
    - CODECOV_TOKEN=7ab7e761-055f-4ed0-bbbd-69d02d25faec
    - secure: "Tq9LnonteZMoeYslQizQx9bc+FeSHzM6L+0xqALNTaqMZzg3HODTkZN3BBrxQWi1aQKEQNkVYJ3X37lFl9kYcu15MQOVU3/jNwYgRqK+mhoa2Sjo1EIcyqTHFkZcyLZmqwQ4qhOeTOz5J6hnXU7NQZMX65WTAfT2wBiDTsiCD6vadFlAk7CRQDXuPHqJhWfM57w08nWFXISxgwsrOFBKJPJp9ur8Ht2d/iWId1v8p69RUzPgoTIllxcmhUvTT4oZWoDwPZZfIhFDXVWdr5STrmZ6iaThh3o6vcMiBabP1VZjEiDpd+1bHgkjy1WhkcPaG6ushMWc+Rzolcie4PtrpxXMyRYSTNN554nyEJXfmsqY1/KN9rINKFMCYmDNG99X+1kBh5YCJMQSWH8+2TxkP8zo9iLsgaDbQzL4MbxZhjPXO0H1rkaRUB2wmcb1hBTP55YbI+KsKW2mt/jrauWJb1Jv3ZWT+RSL3cZ6m6Kx0GP9ngjIEzuZMCeIok4SHrpwz826qT2JgS/LW5yuTdGKih2E40EMXLWb2rUEygaKvlyhgTbdxFepbGJ4M2r0b65oL7kdJcF4WHH0WoeQy0JlLIBHA5mhMCOjXZXd2UbRPbtOX2PDNrZ1ZQkUXHuU02BUvEZc+4WtlXM/KhderHTfKxY55LyDiUO1+n8pVekCbws="
before_install:
  - composer config --global github-oauth.github.com "$REACT_APP_GET_ME_IN"
after_success:
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
script:
  - npm test
  - npm run test:coverage
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $secure
  local_dir: build
  on:
    branch: master
