language: node_js
node_js:
  - 11.10.1
cache:
  directories:
    - node_modules
env:
  global:
    - CODECOV_TOKEN=7ab7e761-055f-4ed0-bbbd-69d02d25faec
after_success:
  - git config --global user.name "mr-bagglesworth"
  - git config --global user.email "mr-bagglesworth@users.noreply.github.com"
  - git remote rm origin
  - git remote add origin https://mr-bagglesworth:${REACT_APP_GET_ME_IN}@github.com/mr-bagglesworth/Github-GraphQL.git
  - npm run deploy
  - bash <(curl -s https://codecov.io/bash) -e TRAVIS_NODE_VERSION
script:
  - npm test
  - npm run test:coverage
  - npm run build
